### PR TITLE
install gfortran on macos

### PR DESCRIPTION
**Pull request by hainm**

### CODE REVIEW

**Comment by multiplemonomials** [comment]
Sorry to butt in, but I thought it might be helpful: If you use cpptraj's CMake build system, then you do not need to supply a Fortran compiler as long as `libfftw` is installed.

**Comment by hainm** [comment]
Cool. Thanks Jamie.

Ps; i really dont know why pytraj cron builld on macos failed recently.
Travis might have changed something.

Hai

**Comment by slochower** [comment]
This may be related. I'm unable to import `pytraj` on macOS 10.13.3 due to a `libgfortran` error after installing via the AmverTools conda channel.

```python 
$ python
Python 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:54:01)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytraj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dslochower/anaconda3/envs/paprika/lib/python3.6/site-packages/pytraj/__init__.py", line 23, in <module>
    from .utils.misc import info
  File "/Users/dslochower/anaconda3/envs/paprika/lib/python3.6/site-packages/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/Users/dslochower/anaconda3/envs/paprika/lib/python3.6/site-packages/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: dlopen(/Users/dslochower/anaconda3/envs/paprika/lib/python3.6/site-packages/pytraj/core/topology_objects.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/gfortran/lib/libgfortran.3.dylib
  Referenced from: /Users/dslochower/anaconda3/envs/paprika/lib/libcpptraj.dylib
  Reason: image not found
```

**Comment by hainm** [comment]
hi @slochower, which conda channel you're using? 

We have an official version here: http://ambermd.org/GetAmber.php
```
conda install ambertools=17 -c http://ambermd.org/downloads/ambertools/conda/
``` 

Let me know if that works for you. Cheers.

**Comment by hainm** [comment]
hi, can you replace `ambertools=17.0` to `ambertools=17` (use exact command I sent earlier) to get the latest version? I think I made the fix after 17.0. Thanks.

**Comment by slochower** [comment]
Ah, perfect! Good catch!

**Pull request merged**
