### PR TITLE
CMake OpenMP Changes

### PR DESCRIPTION
**Pull request by multiplemonomials**
OK, I did what you said, and cherry-picked my 2 commits onto a new branch.  The changes are the same as my previous PR, of course.  Thanks for the advice.

### CODE REVIEW

**Comment by hainm** [comment]
Please address another comment about fixing test too.

**Comment by multiplemonomials** [comment]
Ah, I see what you mean.

**Comment by multiplemonomials** [comment]
Hmmm, the Travis builds are failing with
```
 gcc: error: unrecognized command line option ‘-fstack-protector-strong’
  gcc: error: unrecognized command line option ‘-fno-plt’
```

ANy idea why that's happening?  It looks like GCC is the wrong version.

**Comment by hainm** [comment]
due to psutil compiling. You can remove memory_profiler and psutils install, otherwise, I will do that tonight.

**Comment by multiplemonomials** [comment]
Yeah, I'll... just let you do that one.

**Comment by hainm** [comment]
uhm, Miniconda people decided to compile Python with new gcc compiler (> 4.8) while travis only has gcc 4.8. 

I still need to figure out how to get gcc-5 there.

**Comment by multiplemonomials** [comment]
Sheesh.  Can't you install it through APT?  I feel like I did that in my `ambertools-cmake-ci` port.

**Comment by hainm** [comment]
close this PR in favor of #1427 

(I messed up with your branch, sorry).

**Pull request closed without merging**
