### PR TITLE
info about license

### PR DESCRIPTION
**Pull request by hainm**
not sure I am doing correctly. Comments are welcome.

### CODE REVIEW

**Comment by swails** [comment]
pytraj cannot operate independently of cpptraj, and always links directly to it when you install it.  Therefore, pytraj is considered to be a "derived work" of cpptraj and is bound by the GPL v3.

The only thing that gets you out of having to switch to GPL is if cpptraj is relicensed under a more permissive license, like L-GPL or BSD itself.

Just FYI.  You can see more info about the GPL here: http://www.gnu.org/licenses/gpl-faq.html

**Comment by swails** [comment]
In particular, the "source code" includes compilation materials and scripts (like setup.py and stuff) -- since that downloads, compiles, and links to cpptraj on its own as part of the standard install process, it is a derived work.  An email I sent to the Amber-dev list awhile ago about this: http://dev-archive.ambermd.org/201410/0046.html

**Comment by hainm** [comment]
so your advice is to license pytraj under GPL?  and this is only correct way to do it.

I will read your link carefully.

**Comment by hainm** [comment]
my intention to release pytraj's source code as BSD since sometimes people might want to reuse a piece of code. Just like I asked mdtraj: https://github.com/mdtraj/mdtraj/pull/891

**Comment by drroe** [comment]
> my intention to release pytraj's source code as BSD since sometimes people might want to reuse a piece of code.

I've always been a bit fuzzy on licensing issues, but as far as I know people can re-use your code if it's GPL, they just can't turn around and charge for it (and they have to give credit where credit is due). I have no plans to ever switch cpptraj's license from GPL.

**Comment by hainm** [comment]
ok. to avoid heachdache, I am chaning BSD to GPL v3 for pytraj

on 
- [x] github
- [ ] anaconda channel (conda): https://anaconda.org/AmberMD/pytraj/files
- [x] pypi: https://pypi.python.org/pypi/pytraj

**Comment by swails** [comment]
> I've always been a bit fuzzy on licensing issues, but as far as I know people can re-use your code if it's GPL, they just can't turn around and charge for it (and they have to give credit where credit is due). I have no plans to ever switch cpptraj's license from GPL.

Actually, I can take cpptraj and turn around and sell it.  I can make small changes and sell it as a "new product" (albeit, derived from cpptraj with you retaining the copyright for the parts you wrote and me for my modifications).  However, what the GPL *doesn't* let me do is relicense it using another, more restrictive license.  Which means that if someone wants to buy it from me and I sell it to them, I *must* provide the source code.  And they now have the right to do with it everything that I had the right to do with it.  So while I can sell it, they can give it away for free, and I can't stop them.

BSD and MIT, as I understand it, gives you the right to relicense it as you want (but obviously the original licenses still exist, so if you take BSD or MIT and license it under a closed license, the open licenses still exist).  And if you link to a piece of GPL code, your whole project becomes derived and, therefore, GPL itself.  LGPL lets you keep just the library under an open license and keep the rest closed.

The reason people like Linus Torvalds likes the GPL (v2 -- he dislikes v3 for Linux) is because it basically requires that you make any modifications available upstream (unless you don't release it to *anybody*).  It seems fair that if I release something for free, and person A makes an improvement, I shouldn't be locked out of obtaining that improvement and effectively being forced out of my own project.

**Comment by swails** [comment]
@hainm -- you can license code snippets and pieces independent of cpptraj under whatever license you want (e.g., if someone asks you).  But you can't license pytraj as a whole under something less restrictive than the GPL.

**Comment by hainm** [comment]
> you can license code snippets and pieces independent of cpptraj under whatever license you want (e.g., if someone asks you). But you can't license pytraj as a whole under something less restrictive than the GPL.

I see. thanks.

**Pull request merged**
