### PR TITLE
remove default compiler clang in osx

### PR DESCRIPTION
**Pull request by hainm**

### CODE REVIEW

**Comment by swails** [comment]
I'm close to getting everything working. Don't do this yet, it won't build for AmberTools I don't think.

**Comment by hainm** [comment]
ok @swails. After amber code freeze, I added/changed the set up process a bit without merging back to amber repo. So you should expect the github repo should a bit different. 

But I am ok to revert back to the point that github repo matches to amber repo if this makes your change easier.

**Comment by swails** [comment]
ok, that might complicate things.  By the way, just adding `++` to the OS X C compiler doesn't work in general.  For old distros, "gcc" turns to "gcc++", not "g++".  You're better off just setting both explicitly.  But that's all done in the changes I'm making.

**Comment by hainm** [comment]
> By the way, just adding ++ to the OS X C compiler doesn't work in general. For old distros, "gcc" turns to "gcc++", not "g++". You're better off just setting both explicitly.

yeah, my naive experience to change compiler. :)) Turns out that I just need to export CXX and CC environment. This PR intends to remove dump stuff. 

> But that's all done in the changes I'm making.

:+1:

**Comment by hainm** [comment]
anyway, I just ordered online a Mac pro today. :))

**Pull request closed without merging**
