### PR TITLE
Fix 'hbond' command

### PR DESCRIPTION
**Pull request by drroe**
Action_Hbond has been renamed Action_HydrogenBond; related to Amber-MD/cpptraj#485.

### CODE REVIEW

**Comment by drroe** [comment]
@hainm All test failures seem unrelated to `hbond` - they have to do with `velocityautocorr` etc and it's not clear to me what the failure actually is. Any ideas?

**Comment by hainm** [comment]
have you updated velocity related stuff recently? In cpptraj circleci, we only test pytraj installation. That's why the error was never captured. I think I should turn on nightly run for pytraj on travis.

Per `velocityautocorr`, I don't know why yet. Will investigate tonight.

**Comment by drroe** [comment]
Yes, in Amber-MD/cpptraj#479 and Amber-MD/cpptraj#482 - the former is a bugfix, the latter more cosmetic but the output does change. It seems like this test should be updated:
```
tests/test_analysis/test_velocity.py
```
but it's not clear to me how to update the test (forgive my ignorance).

**Comment by drroe** [comment]
@hainm I think I see the problem. In `velocityautocorr` I introduced a new DataSet, `<name>[D]` (i.e. aspect is [D]), which stores the diffusion constant in 1x10^-5 cm/s (like the `diffusion` command). I think that pytraj is comparing this to the time series instead of the time series itself. The issue is this:
```python
        state = pt.load_cpptraj_state(cm)
        state.run()
        aa_eq(data0, state.data[-1].values)
```
the data[-1] is getting the diffusion constant instead of the velocity autocorrelation function. I'm guessing that the -1 means "get the last data set created", but I'm not sure how to change that to the set I want.

**Comment by hainm** [comment]
You can look at the code here: https://github.com/Amber-MD/pytraj/blob/master/pytraj/all_actions.py#L1776-L1865

Basically, pytraj use (Cpptraj)DatasetList to store the data and convert everything to numpy array (as default). 

Can you try updating the test

```python
aa_eq(data0[0], state.data[-2].values)
```

**Comment by hainm** [comment]
from travis log

```bash
arr0 = array([ array([ 1.        , -0.31652982, -0.05101681, ...,  0.00830873,
       -0.01157217,  0.00187534]),
       array([ 4.41340766])], dtype=object)
arr1 = array([ 4.41340766]), decimal = 4
```

**Comment by hainm** [comment]
I guess you need to add alias for `hbond` here too:

https://github.com/Amber-MD/pytraj/blob/master/pytraj/analysis/c_action/c_action.pyx#L20-L30

```python
ADICT["hbond"] = _ALL['Action_HydrogenBond']
```

**Comment by hainm** [comment]
we almost make it. Final error

```bash
test_docs.py::TestDoc::test_doc **********************************************************************
File "pytraj/analysis/hbond_analysis.py", line 101, in pytraj.analysis.hbond_analysis.hbond
Failed example:
    hbonds.donor_acceptor
Expected:
    ['LYS8_O-GLU5_N-H', 'GLU5_O-LYS8_N-H', 'LYS8_HZ1-V', 'LYS8_HZ2-V', 'GLU5_OE2-V', 'GLU5_O-V', 'GLU5_OE1-V', 'LYS8_HZ3-V']
Got:
    ['LYS8_O-GLU5_N-H', 'GLU5_O-LYS8_N-H', 'GLU5_OE2-V', 'GLU5_O-V', 'LYS8_HZ2-V', 'GLU5_OE1-V', 'LYS8_HZ1-V', 'LYS8_HZ3-V']
**********************************************************************
1 items had failures:
   1 of   9 in pytraj.analysis.hbond_analysis.hbond
***Test Failed*** 1 failures.
```

**Comment by drroe** [comment]
The loop refactoring (key to single-threaded speed increase) has led to time series data sets being added in slightly different order. Does pytraj support data set sorting? If not just need to update to the new ordering.

**Comment by drroe** [comment]
`pytraj/analysis/hbond_analysis.py` is the correct file to update right?

**Comment by hainm** [comment]
> pytraj/analysis/hbond_analysis.py is the correct file to update right?

Yes, you can add `sorted`:

https://github.com/Amber-MD/pytraj/blob/master/pytraj/analysis/hbond_analysis.py#L52

```python
return sorted(self.data.grep(["solventhb", "solutehb"], mode='aspect').keys())
```

**Comment by hainm** [comment]
> If not just need to update to the new ordering.

I think you need to update it too.

**Comment by drroe** [comment]
I've exhausted the time I have to look at this for now and I'm having trouble with getting a clean python 3 environment to run so I can reproduce this error so I'm tabling this for now. May try to get to it later but odds are not good - will be extremely busy the next week or so. This is at least a good start.

**Comment by hainm** [comment]
I can fix it tonight. don't worry.

**Comment by hainm** [comment]
thanks Dan.

**Comment by hainm** [comment]
> python 3 environment to run so I can reproduce this error so I'm tabling this for now.

FYI: 

```bash
conda create -n py3 python=3.6 numpy
source activate py3
# source deactivate py3
```

**Comment by hainm** [comment]
finally. thanks.

**Pull request merged**
