### PR TITLE
Update pytraj for new cpptraj molecule handling

### PR DESCRIPTION
**Pull request by drroe**
Changes needed for pytraj to work after https://github.com/Amber-MD/cpptraj/pull/845 is merged. 

@hainm can you double check that all looks ok? Once I get the green light from you I can merge cpptraj 845 and then this can be merged,

I note there is this in the test output:
```
test_trajectory/test_trajectory_writer.py::test_trajectory_writer_open_close Internal Error: TrajoutList::AddTrajout() called with empty filename.
Error: Could not determine trajectory '/tmp/tmpxad332b8/test.x' format.
Error: Could not set up trajectory '/tmp/tmpxad332b8/test.x'
PASSED
```
However, this seems to be present in master as well so I don't think it's related to this PR.

### CODE REVIEW

**Comment by drroe** [comment]
@hainm out of curiosity why was `test_convert_to_dict_and_rebuild` removed?

**Comment by hainm** [comment]
> @hainm out of curiosity why was test_convert_to_dict_and_rebuild removed?

Because it duplicates the code in `__setstate__`: https://github.com/Amber-MD/pytraj/blob/30fb774d117d4cd5792c36af405282c93a8fbe6c/pytraj/topology/topology.pyx#L762

The tests for `__setstate__` are covered in those: https://github.com/Amber-MD/pytraj/blob/66e181535900dbac6befb357302a3bf8f6c6ceb3/tests/test_pickle.py#L50-L60

**Comment by hainm** [comment]
@drroe Thanks. I go ahead merging this PR, it does not depend on https://github.com/Amber-MD/cpptraj/pull/845

**Comment by drroe** [comment]
Thanks @hainm !

**Pull request merged**
