### PR TITLE
WIP: The ReplaceAsterisk() function has been deprecated.

### PR DESCRIPTION
**Pull request by drroe**
This should fix the breakage caused by https://github.com/Amber-MD/cpptraj/pull/777

Should be considered WORK IN PROGRESS until that PR is accepted.

### CODE REVIEW

**Comment by hainm** [comment]
>  until that PR is accepted.

What do you mean about "accepted"?

**Comment by drroe** [comment]
> What do you mean about "accepted"?

Until I merge the cpptraj PR, pytraj will be pulling from the master (which still has the ReplaceAsterisk function).

**Comment by hainm** [comment]
uhm, do you mean that you still merge cpptraj even it fails `pytraj`? I thought we should fix pytraj before merging cpptraj.

**Comment by hainm** [comment]
> fix pytraj 

Remove unused functions that block `cpptraj` merge.

**Comment by drroe** [comment]
> uhm, do you mean that you still merge cpptraj even it fails pytraj

Only in the case that merging is necessary to get the pytraj test to pass. That's not the case though, all tests have passed. This should be good to merge.

**Comment by drroe** [comment]
@hainm I will let you do the merge if you are comfortable with the changes. Once it's merged I'll retrigger the Jenkins build for cpptraj.

**Comment by hainm** [comment]
thanks @drroe

**Comment by swails** [comment]
> Should be considered WORK IN PROGRESS until that PR is accepted.

There was no reason for this function to be exposed in pytraj, though.  Removing it doesn't actually hurt anything :smiley:

**Comment by hainm** [comment]
> There was no reason for this function to be exposed in pytraj, though.

yeah, that's from the old time when I started learning stuff, very naive.

**Comment by drroe** [comment]
> yeah, that's from the old time when I started learning stuff, very naive.

Ha, that's funny - I feel the same way about the NameType class, which is what led to the PR in the first place...

**Pull request merged**
